# Определение сервиса для доступа к MySQL в Kubernetes
apiVersion: v1  # Версия API Kubernetes, используемая для создания сервисов
kind: Service  # Указываем, что создаём объект типа Service
metadata:
  name: mysql-db  # Имя сервиса, через которое будет доступен кластер MySQL
spec:
  selector:
    app: mysql  # Селектор, определяющий, какие поды будут обслуживаться этим сервисом
               # Сервис будет направлять трафик на все поды с меткой "app=mysql"
  ports:
    - port: 3306  # Порт, на котором сервис будет доступен внутри Kubernetes кластера
      # Контейнер MySQL по умолчанию слушает на порту 3306
  clusterIP: None  # Устанавливаем "None", чтобы создать headless-сервис
                  # Это означает, что Kubernetes не будет выделять один IP для этого сервиса.
                  # Вместо этого будет использоваться DNS, который разрешит имена подов в сервисе.
                  # Это важно для StatefulSet, так как каждый под должен быть доступен по уникальному имени.
