services:
  app:
    build: .
    container_name: flask_app
    ports:
      - "5001:5000"
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - FLASK_SECRET_KEY=your-very-secret-key
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: flask_db
    environment:
      - POSTGRES_USER=your_user
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_DB=flaskdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
