# Generated by Django 5.1.3 on 2025-01-05 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='qr_codes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='links.link')),
            ],
        ),
    ]
